name: "nakama-node-1"
data_dir: "/nakama/data/"

runtime:
  path: "/nakama/data/modules/"

logger:
  level: "debug"
  file: ""
  stdout: true

socket:
  port: 7350
  max_message_size_bytes: 4096

session:
  allowed_origin: ["*"]

matchmaker:
  interval_sec: 1

# "Direct Lobby" system:
#   Client-Side: When clicking "Play", the client searches for any active match with a label like "open".
#   Server-Side: If a match is found, the player joins immediately. If not, the player creates a new one.

console:
  port: 7351
  username: "admin"
  password: "password"
